server:
  port: 2001
  servlet:
    contextPath: /
mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/**/*.xml
  type-aliases-package: com.angel.common.*.entity
spring:
  profiles:
    active: dev
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
security:
  oauth2:
    ignored: /error/**,/oauth/token ,/oauth/user/token , /oauth/client/token   ,/user/logout ,/document.html,/webjars/**,/resources/**,/i18n/**
    authorization:
      check-token-access: true
    client:
      access-token-uri: http://localhost:2000/oauth/token
      user-authorization-uri: http://localhost:2000/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:2000/user
      prefer-token-info: false
      filter-order: 3
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
    register-with-eureka: true
    fetch-registry: false