spring:
  profiles:
    active: dev
  application:
    name: angel-gen
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
server:
  compression:
    enabled: true
    min-response-size: 10
    excluded-user-agents: gozilla,traviata
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
