server:
  port: 10080
  servlet:
    context-path: /
spring:
  application:
    name: angel-gateway-service
  redis:
    host: 111.207.248.47
    port: 16379
  cloud:
    gateway:
      routes:
        - id: message
          uri: http://localhost:8080
          predicates:
            - Path=/message/{path}
          filters:
            # 访问localhost:10080/message, 请求会转发到localhost:8080
            - RewritePath=/message, /
        - id: user
          uri: http://localhost:9090
          predicates:
            - Path=/user/{path}
          filters:
            # 访问localhost:10080/user, 请求会转发到localhost:8080
            - RewritePath=/user, /

