server:
  port: 9090
  session:
    cookie:
      name: USERSESSION
  servlet:
    contextPath: /
  application:
    name: user-service
mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/**/*.xml
  type-aliases-package: com.angel.common.*.entity
spring:
  profiles:
    active: dev
  application:
    name: user-service
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
    register-with-eureka: true
    fetch-registry: true
feign:
  hystrix:
    enabled: true
security:
  basic:
    enabled: false
  headers:
    frame: true
  oauth2:
    client:
      accessTokenUri: http://localhost:2000/oauth/token
      authorized-grant-types: authorization_code,refresh_token
      clientAuthenticationScheme: header
      clientId: curl_client
      clientSecret: user
      useCurrentUri: true
      userAuthorizationUri: http://localhost:2000/oauth/authorize
    resource:
      userInfoUri: http://localhost:2000/user
