spring:
  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35729
    restart:
      enabled: true #是否支持热部署
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  mvc:
    #static 文件夹下的静态文件访问路径
    static-path-pattern: /**
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: ppzAdmin
    dynamic:
      druid:
        filters: stat,wall
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 5000
        useGlobalDataSourceStat: true
      p6spy: true # 默认false,建议线上关闭。
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master_1:
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/angel-oauth?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: angel-spring
          password: angel-spring@123
          # 初始化大小，最小，最大
          initialSize: 5
          maxActive: 500
          maxPoolPreparedStatementPerConnectionSize: 20
          # 配置获取连接等待超时的时间
          maxWait: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 300000
          minIdle: 5
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          testOnBorrow: false
          testOnReturn: false
          testWhileIdle: true
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          validationQuery: SELECT 1 FROM DUAL
        slave_1:
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/angel-oauth?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: angel-spring
          password: angel-spring@123
          # 初始化大小，最小，最大
          initialSize: 5
          maxActive: 500
          maxPoolPreparedStatementPerConnectionSize: 20
          # 配置获取连接等待超时的时间
          maxWait: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 300000
          minIdle: 5
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          testOnBorrow: false
          testOnReturn: false
          testWhileIdle: true
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          validationQuery: SELECT 1 FROM DUAL