server:
  port: 2000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    contextPath: /auth
    session:
      cookie:
        name: AUTHSESSIONID
mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/**/*.xml
  type-aliases-package: com.angel.common.*.entity
spring:
  profiles:
    active: dev
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
#security:
#  oauth2:
#    ignored: /error/**,/oauth/authorize,/oauth/token ,/oauth/user/token , /oauth/client/token   ,/user/logout ,/document.html,/webjars/**,/resources/**,/i18n/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
    register-with-eureka: true
    fetch-registry: false