server:
  port: 1000
spring:
  application:
    name: eureka-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
    register-with-eureka: true
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
logging:
  level:
    com.netflix: info