server:
  port: 8080
  servlet:
    contextPath: /
    session:
      cookie:
        name: MESSAGESESSIONID
  application:
    name: user-service
mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/**/*.xml
  type-aliases-package: com.angel.common.*.entity
spring:
  profiles:
    active: dev
  application:
    name: user-service
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  main:
    allow-bean-definition-overriding: true
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
    register-with-eureka: true
    fetch-registry: true
feign:
  hystrix:
    enabled: true
security:
  oauth2:
    sso:
      login-path: /login
    client:
      accessTokenUri: http://127.0.0.1:2000/auth/oauth/token
      authorized-grant-types: authorization_code,password,refresh_token,implicit,client_credentials
      clientAuthenticationScheme: header
      clientId: message-service
      clientSecret: user
      scope: read,write
      useCurrentUri: true
      userAuthorizationUri: http://127.0.0.1:2000/auth/oauth/authorize
    resource:
      id: product_api
      userInfoUri: http://127.0.0.1:2000/auth/user
    authorization:
      check-token-access: http://127.0.0.1:2000/auth/oauth/check_token
