server:
  port: 2000
  servlet:
    contextPath: /
mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/**/*.xml
  type-aliases-package: com.angel.common.*.entity
spring:
  profiles:
    active: dev
  application:
    name: auth-service
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: req
    suffix: .html
    template-loader-path: classpath:/templates
    settings:
      number_format: 0.##
security:
  oauth2:
    ignored: /error/**,/oauth/token ,/oauth/user/token , /oauth/client/token   ,/user/logout ,/document.html,/webjars/**,/resources/**,/i18n/**
    resource:
      filter-order: 3
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
    register-with-eureka: true
    fetch-registry: false